## PyRamen

### I did not do what the question asked as it was asked, rather I used pandas to more easily come up with the same results, and export as a .csv rather than a .txt

In [1]:
import pandas as pd # import pandas

#read in csvs, instantiate them as variables
menudatadf = pd.read_csv('menu_data.csv')
salesdatadf = pd.read_csv('sales_data.csv')

#rename 'Menu_item' to 'item' for csv merge
salesdatadf = salesdatadf.rename({'Menu_Item' : 'item'}, axis = 'columns')

#Drop useless columns from each csv
salesdatadf = salesdatadf.drop(columns = ['Line_Item_ID','Date', 'Credit_Card_Number'])
menudatadf = menudatadf.drop(columns = ['category','description'])

#Merge the two datasets
dfjoin = pd.merge(menudatadf,salesdatadf, on = 'item', how = 'inner')

#Rename quantity column to count as question requests
dfjoin = dfjoin.rename({'Quantity' : 'Count'}, axis = 'columns')

#Calculate revenue and cost of goods sold
dfjoin['Revenue'] = dfjoin['price'] * dfjoin['Count']
dfjoin['COGS'] = dfjoin['cost'] * dfjoin['Count']

#drop the now useless price and cost columns
dfjoin = dfjoin.drop(columns = ['cost','price'])

#import NumPy to aggregate each item's statistics
import numpy as np

#Aggregate and sum the count, revenue, and cost of goods to each specific item
dfpivot = pd.pivot_table(dfjoin , values=['Count', 'Revenue', 'COGS'] , index=['item'], aggfunc = np.sum)

#Calculate the profit and append it to the dataset
dfpivot['Profit'] = dfpivot['Revenue'] - dfpivot['COGS']

#Reorder columns to order question specifies
dfpivot = dfpivot[['Count' , 'Revenue' , 'COGS' , 'Profit']]

#export dataset as a csv
dfpivot.to_csv('PyRamen_Final_Dataset.csv')

#print dataset to terminal
dfpivot

,Count,Revenue,COGS,Profit
item,,,,
burnt garlic tonkotsu ramen,9070,126980.0,54420,72560.0
miso crab ramen,8890,106680.0,53340,53340.0
nagomi shoyu,9132,100452.0,45660,54792.0
shio ramen,9180,100980.0,45900,55080.0
soft-shell miso crab ramen,9130,127820.0,63910,63910.0
spicy miso ramen,9238,110856.0,46190,64666.0
tonkotsu ramen,9288,120744.0,55728,65016.0
tori paitan ramen,9156,119028.0,54936,64092.0
truffle butter ramen,8982,125748.0,62874,62874.0
vegetarian curry + king trumpet mushroom ramen,8824,114712.0,61768,52944.0
vegetarian spicy miso,9216,110592.0,46080,64512.0